# Generated by Django 5.1.1 on 2024-10-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
